import torch
import fastapi
import typer
import loguru
import uvicorn
import gradio
import diffusers
import transformers
import PIL
import numpy
import yacs
import piexif
import omegaconf
import easydict
import socketio
import huggingface_hub
import accelerate
import peft
import safetensors
import controlnet_aux

print("所有依赖都能 import，环境没问题！")