directories:
  output: release
  buildResources: build
appId: com.watermagician.app
productName: 水印魔术师
files:
  - filter:
      - dist/**/*
      - main.js
      - web_app/dist/**/*
      - main.py
      - iopaint/**/*
      - requirements.txt
extraResources:
  - to: Resources
    filter:
      - main.py
      - iopaint/**/*
      - requirements.txt
mac:
  icon: build/icons/icon.png
  target:
    - dmg
electronVersion: 36.4.0
