directories:
  output: release
  buildResources: build
appId: com.watermagician.app
productName: 水印魔术师
files:
  - filter:
      - dist/**/*
      - main.js
      - web_app/dist/**/*
      - models/**/*
extraResources:
  - from: build/python
    to: Resources/python
  - from: models
    to: Resources/models
  - to: Resources
    filter:
      - iopaint/**/*
mac:
  icon: build/icons/icon.png
  target:
    - dmg
electronVersion: 36.4.0
