directories:
  output: release
  buildResources: build
appId: com.iopaint.app
productName: IOPaint
files:
  - filter:
      - dist/**/*
      - main.js
      - preload.js
      - iopaint/**/*
      - '!iopaint/__pycache__'
      - requirements.txt
mac:
  category: public.app-category.graphics-design
win:
  target: nsis
linux:
  target: AppImage
electronVersion: 36.4.0
